name: dynaavatar_release
channels:
  - nvidia          
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - cuda-nvcc=12.8
  - cuda-toolkit=12.8  
  - eigen
  - zlib
  - libcusparse-dev
  - libcublas-dev
  - libcusolver-dev
  - libcudnn             
  - cusparselt         
  - cusparselt-dev 
  - libnvjitlink-dev     
  - libcufft-dev         
  - libcurand-dev        
  - libnpp-dev           
  - libnvjpeg-dev        
         

# conda env create -f base.yml

